version: '3.8'

services:
  parser:
    build: ./parser
    ports:
      - "3000:3000"
    volumes:
      - ./parser:/usr/src/app
    command: npm start

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/usr/src/app

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  kafka:
    driver: bridge
