version: '3.8'

services:
  parser:
    build: ./parser
    volumes:
      - ./parser:/usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PYTHON_PARSER_PATH=./parser.py
      - PROMPT_PATH=./prompt.txt
    ports:
      - "3000:3000" # DEBUG, in prod solo Kafka
    depends_on:
      - kafka
    networks:
      - kafka

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/usr/src/app
    depends_on:
      - kafka
    networks:
      - kafka

  kreader_test:
    build: ./reader
    volumes:
      - ./reader:/usr/src/app
    depends_on:
      - kafka
    networks:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

   #remote_chrome:
   #  image: 'selenium/standalone-chrome'
   #  shm_size: '1gb'
   #  ports:
   #    - "4444:4444"
   #    - "7900:7900"

   #  networks:
   #    - remote_chrome

volumes:
  kafka_data:
    driver: local

networks:
  kafka:
    driver: bridge
  #remote_chrome:
    #driver: bridge
