version: '3.8'

services:
  parser:
    build: ./parser
    volumes:
      - ./parser:/usr/src/app
    environment:
      - NODE_ENV=development
      - PROMPT_PATH=./prompt.txt
    ports:
      - '3000:3000' # DEBUG!!
    networks:
      - kafka

  # telegram-bot:
  #   build: ./telegram-bot
  #   volumes:
  #     - ./telegram-bot:/usr/src/app
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - PROMPT_PATH=./prompt.txt
  #   depends_on:
  #     parser:
  #       condition: service_started
  #     kafka:
  #       condition: service_healthy
  #   networks:
  #     - kafka

  # scraper:
  #   build: ./scraper
  #   volumes:
  #     - ./scraper:/usr/src/app
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     # rotating_tor:
  #     #   condition: service_healthy
  #   networks:
  #     - kafka

  # kreader_test:
  #   build: ./reader
  #   volumes:
  #     - ./reader:/usr/src/app
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     scraper:
  #       condition: service_started
  #   networks:
  #     - kafka

  # NOTA: usato SOLO COME DEBUG per il parser, TOGLI IN PRODUZIONE
  parser-tester:
    build: ./parser-tester
    volumes:
      - ./parser-tester:/usr/src/app
    depends_on:
      parser:
        condition: service_started
    networks:
      - kafka


  # rotating_tor:
  #   image: 'mattes/rotating-proxy'
  #   restart: unless-stopped
  #   # volumes:
  #   #   - ./torproxy/torrc:/etc/tor/torrc
  #   ports: # expose solo per debug
  #     - "5566:5566"
  #     - "4444:4444"
  #   environment:
  #     - tors=25
  #   networks:
  #     - rotating_tor
  #   healthcheck:
  #     test: ["CMD", "curl", "--proxy", "http://rotating_tor:5566", "https://api.myip.com/"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 30s

  # kafka:
  #   image: 'bitnami/kafka:latest'
  #   networks:
  #     - kafka
  #   healthcheck:
  #     test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe || exit 1"]
  #     start_period: 30s
  #     interval: 5s
  #     timeout: 10s
  #     retries: 5
  #   environment:
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #     - KAKFA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #     - FIRST_BROKER_ID=1001
  #   logging:
  #     driver: none # DEBUG - togli se necessario

   #remote_chrome:
   #  image: 'selenium/standalone-chrome'
   #  shm_size: '1gb'
   #  ports:
   #    - "4444:4444"
   #    - "7900:7900"

   #  networks:
   #    - remote_chrome

volumes:
  kafka_data:
    driver: local

networks:
  kafka:
    driver: bridge

  rotating_tor:
    driver: bridge
  #remote_chrome:
    #driver: bridge
