version: "3.8"

services:
  parser:
    build: ./parser
    volumes:
      - ./parser:/usr/src/app
    environment:
      - NODE_ENV=development
      - PROMPT_PATH=./prompt.txt
    ports:
      - "3000:3000" # DEBUG!!
    networks:
      - rabbitmq-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-consumer:
        condition: service_healthy

  # telegram-bot:
  #   build: ./telegram-bot
  #   volumes:
  #     - ./telegram-bot:/usr/src/app
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - PROMPT_PATH=./prompt.txt
  #   depends_on:
  #     parser:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - rabbitmq-network

  # scraper:
  #   build: ./scraper
  #   volumes:
  #     - ./scraper:/usr/src/app
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     db-consumer:
  #       condition: service_healthy
  #   networks:
  #     - rabbitmq

  # kreader_test:
  #   build: ./reader
  #   volumes:
  #     - ./reader:/usr/src/app
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     scraper:
  #       condition: service_started
  #   networks:
  #     - rabbitmq-network

  # NOTA: usato SOLO COME DEBUG per il parser, TOGLI IN PRODUZIONE CHE DIVENTI POVERO
  # parser-tester:
  #   build: ./parser-tester
  #   volumes:
  #     - ./parser-tester:/usr/src/app
  #   depends_on:
  #     parser:
  #       condition: service_started
  #   networks:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5672:5672" # DEBUG
      - "15672:15672" # DEBUG (Web UI)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network

  mongodb:
    image: mongo:6.0.7-jammy
    ports:
      - "27018:27017" # per non collidere con il db locale
    volumes:
      - db-data:/data/db
    networks:
      - db-network # non esporlo ad altri servizi se non db-api
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  db-consumer:
    build: ./db-consumer
    volumes:
      - ./db-consumer:/usr/src/app
    ports:
      - "3434:3434" # DEBUG - ha solo una route /ping per verificare che worka
    environment:
      - NODE_ENV=development
      - PING_SERVER_PORT=3434
    depends_on:
      db-api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:3434/ping || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  db-api:
    build: ./db-api
    volumes:
      - ./db-api:/usr/src/app
    ports:
      - "5500:5500" # DEBUG - hard-coded nella config di db-consumer
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/debug
      - PORT=5500
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - db-network
      - rabbitmq-network
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q -O- http://localhost:5500/api/ping || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  rabbitmq-network:
    driver: bridge
  db-network:
    driver: bridge
