export interface AppError {
    err: Errors;
}

export enum Errors {
    KAFKA_RECEIVED_INVALID_TOPIC = "KAFKA_RECEIVED_INVALID_TOPIC",
    KAFKA_RECEIVED_MALFORMED_JSON_DATA = "KAFKA_RECEIVED_MALFORMED_JSON_DATA",
    KAFKA_RECEIVED_EMPTY_PAYLOAD = "KAFKA_RECEIVED_EMPTY_PAYLOAD",
    KAFKA_RECEIVED_INVALID_RAW_DATA = "KAFKA_RECEIVED_INVALID_RAW_DATA",
    KAFKA_RECEIVED_INVALID_PARSED_DATA = "KAFKA_RECEIVED_INVALID_PARSED_DATA",
    RAW_DB_SAVE_FAILED = "RAW_DB_SAVE_FAILED",
    PARSED_DB_SAVE_FAILED = "PARSED_DB_SAVE_FAILED"
}
