export interface AppError {
    err: Errors;
}

export enum Errors {
    RABBITMQ_RECEIVED_INVALID_TOPIC = "RABBITMQ_RECEIVED_INVALID_TOPIC",
    RABBITMQ_RECEIVED_NULL_MESSAGE = "RABBITMQ_RECEIVED_NULL_MESSAGE",

    RAW_VALIDATION_FAILED = "RAW_VALIDATION_FAILED",
    PARSED_VALIDATION_FAILED = "PARSED_VALIDATION_FAILED",

    RAW_DB_SAVE_FAILED = "RAW_DB_SAVE_FAILED",
    PARSED_DB_SAVE_FAILED = "PARSED_DB_SAVE_FAILED",

    RAW_DB_CHECK_FAILED = "RAW_DB_CHECK_FAILED",
    PARSED_DB_CHECK_FAILED = "PARSED_DB_CHECK_FAILED"
}
